version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn ng build --prod --build-optimizer --no-progress
      - run: yarn ng test --single-run --no-progress

  deploy:
        working_directory: ~/project
        docker:
            - image: circleci/node:6.10-browsers
        steps:

workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build